services:
  discovery-service:
    image: ahmetcansahin/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
  api-gateway:
    image: ahmetcansahin/apigateway
    ports:
      - 8081:8081
    mem_limit: 700m
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root