services:
  discovery-service:
    image: ahmetcansahin/discoveryserver
    ports:
      - 8761:8761
    mem_limit: 700m
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev